### PR TITLE
"Confirm delete" page.

### PR DESCRIPTION
**Pull request by jensj**
Added a "Confirm delete" page which posts back to controller to perform delete of an object.

Rationale: GET requests should be idempotent.

### CODE REVIEW

**Comment by erichexter** [comment]
I added some comments to the pull request... its close, just need to clean
the implementation up a little bit.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by erichexter** [comment]
I need to merge this in..

**Comment by jensj** [comment]
Not following, you ned me to do something?

**Comment by erichexter** [comment]
I did a bunch of refactoring and moving files around so I will just need to
manually make these changes to the files to get this merged in.. Nothing
you need to do.

Thanks,
Eric

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by serra** [comment]
I'll do this, need to do it anyway for the delete code template.

**Comment by serra** [comment]
@jensj - please close this pull request in favor of #65; files got renamed and somewhere along the way and your commits "got lost" (at least I couldn't find them quick enough).

**Comment by jensj** [comment]
Sure, no problem.

**Pull request closed without merging**
