### PR TITLE
 Add support for specifying a namespace for controllers 

### PR DESCRIPTION
**Pull request by serra**
When working with `Area`s , we can have two or more controllers with the same name in an mvc app, which leads to the following exception when using `MapNavigationRoute`:

```
Multiple types were found that match the controller named 'Home'. This can happen if the route that 
services this request ('') does not specify namespaces to search for a controller that matches the 
request. If this is the case, register this route by calling an overload of the 'MapRoute' method that 
takes a 'namespaces' parameter.
```

To specify routes, we need to be able to specify a namespace, which should be added to `newRoute.DataTokens["Namespaces"]`. Implemented this the same way as `System.Web.Mvc.RouteCollectionExtensions.MapRoute(... string[] namespaces ...)`.

I noticed some commented code `MapNavigationRoute<T>` that wanted to do something with the namespace of the controller. Maybe we can combine this?

### CODE REVIEW

**Comment by serra** [comment]
Is this what you'd like to see? I've merged in your changes up until c1a1ffc9b153656c70ad5f0a51d55f47a025912f (child route support).

**Comment by erichexter** [comment]
yes that looks good.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by erichexter** [comment]
can you merge this with the upstream changes?

**Comment by serra** [comment]
Will do that, but it might have to wait until Monday.

**Comment by serra** [comment]
Is merged to head of master branch, see https://github.com/erichexter/twitter.bootstrap.mvc/network

**Pull request merged**
