### PR TITLE
Some fixes with the sample nuget package

### PR DESCRIPTION
**Pull request by tikrimi**
Removing "@using MvcApplication1" in _BootstrapLayout views. The referrence is not used, and causes an error if you use an other namespace than "MvcApplication1".

Adding ExampleLayouts views in the sample nuget package

### CODE REVIEW

**Comment by erichexter** [comment]
awesome.. I had that fixed locally but did not get a chance to push it..
thank!

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by tikrimi** [comment]
Sorry, I'm a beginner with GitHub. Next time I will do a branch to not have 2 commits that deal with different things in one issue.

**Comment by erichexter** [comment]
I went thru this last night.. I will remove my original layout and use the
basic one as the main layout going forward.  There are some form styling in
the layouts, I think should be removed from the layouts and put into the
views that need them... login.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by erichexter** [comment]
I appreciate your pull request, will please submit this contributor agreement. http://sdrv.ms/13eMRXm this will help keep the project compliant with our open source license.

**Pull request merged**
