### PR TITLE
adding some sample layouts as per Issue #11

### PR DESCRIPTION
**Pull request by davidalpert**
Is this what you had in mind? (re Issue #11)

### CODE REVIEW

**Comment by davidalpert** [comment]
Updated the branch. Still not all the way there but resolved some of the merge issues.

**Comment by erichexter** [comment]
Thanks so much!

**Comment by jjwilliams42** [comment]
Good job guys - I like where this is headed. Although I'm having issues trying to get the example layouts / routes to register. I still only get the default page. Is there somewhere else that I am missing to register these navigation routes?

Thanks!

image

**Comment by erichexter** [comment]
I am just putting the example routes in now.. it includes showing an
example of a child route.  Should have it pushed in the next 10 mins.. you
can pull it from the private nuget feed.. look at the main readme on the
project page for the exact url

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by jjwilliams42** [comment]
Saweeeeet. Already browsing the private nuget feed, I'll check back shortly. Unless my meds kick in first :). Thanks for the prompt reply!

**Comment by erichexter** [comment]
try version 1.0.71 - I think that is the release candidate for the current
trunk

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by jjwilliams42** [comment]
Works like a charm - thanks!

**Comment by erichexter** [comment]
great.. i think im going to push this version to the public nuget feed.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Pull request merged**
