### PR TITLE
Added support for roles in navigation routes

### PR DESCRIPTION
**Pull request by ilivewithian**
I've added support to the Navigation routes for option user roles. If a roles is specified and the user is not in the role, the link will not render.

### CODE REVIEW

**Comment by erichexter** [comment]
I like where your going with this.. I think I will need to add a unit test project to start getting tests around this code. before we start extending it more.

**Comment by ilivewithian** [comment]
Yes, I completely agree. It felt odd sending a pull request without tests.

**Comment by erichexter** [comment]
I am adding project, unit test project.. and a solution now.once i push it we can get this concept into the codebase

**Comment by erichexter** [comment]
I just pushed the NavigationRoutes project and unit tests. we can start adding role based features to this now.

**Comment by ilivewithian** [comment]
I just pulled the latest version, but I can't see the sln or unit tests. Am I just missing something really obvious?

**Comment by erichexter** [comment]
it is kind of buried in the codebase..
https://github.com/erichexter/twitter.bootstrap.mvc/tree/master/src/NavigationRoutes

I think going forward.. once we get the apis worked out.. we will want to
move navigation routes into a separate code repository.. it is already
a separate nuget package.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by serra** [comment]
Instead of specifying the role in the navigation route, would it be possible to use the authorization metadata from the target action or controller?

**Comment by erichexter** [comment]
Im on the same page with you.. I implemented a filter collection, that
allows you to register filters that can remove a route for building the
menu for the current request.  That will enable, removing routes by their
Authorization attributes. Remove based on authenticated state, think,
login,logout, my account scenarios.. ect.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Pull request closed without merging**
