### PR TITLE
Add support for adding Bootstrap Glyphs to action links

### PR DESCRIPTION
**Pull request by serra**
Please review the api d417fe45e4aea023ecd8f91a2604e8504dd55695:

``` html
<li>@Html.ActionLinkWithGlyphIcon(Url.Action("Delete", routevalues),
            "Delete",
            GlyphIcons.remove)</li> 
```

I would have liked something similar to:

``` html
<li>@Html.ActionLink("Delete", "Delete", routevalues)
                   .WithGlyph(GlyphIcons.remove))</li> 
```

But couldn't figure out to achieve that without some horrible string manipulation (or including html agility pack).

### CODE REVIEW

**Comment by erichexter** [comment]
im kind of on the fence about creating strongly typed helpers for rendering html... there is another project called bootstrap extensions that is targeting this.. If we were to start doing this, I would probably want to keep all of these type of view helper extensions in a separate nuget package, that would be totally optional.

**Comment by erichexter** [comment]
Can you move this into a new extensions file. and create a new package
nuspec for this?

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by serra** [comment]
I see your point. I did a quick search for the extension project you mention, but couldn't really find it. Got a link, so I can check it out? Probably better to use that project instead of rolling out something similar, especially since I consider myself somewhat novice in this particular area.

**Comment by erichexter** [comment]
I just saw a nuget, ill look for the project.. but for now, we can build
them into this project, we just need to build them as a separate feature..
which means a separate folder, namespace and nuget package.. if you put the
code in, i will do the rest.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by serra** [comment]
https://github.com/advancedrei/BootstrapForRazor / http://nuget.org/packages/BootstrapForRazor2 ?

**Comment by serra** [comment]
I'll put this in a separate folder and send a new pull request when done.

**Pull request closed without merging**
