### PR TITLE
Support for Vertical/Horizontal Breaks in Navbar

### PR DESCRIPTION
**Pull request by MisterJames**
Added property to NamedRoute to allow composition of break in menu.
Added overloads to accept the flag in the configuration extensions.
Updated navigation extenstions to evaluate and build appropriate tags.
Updated samples.

### CODE REVIEW

**Comment by MisterJames** [comment]
Just a quick note...the git breakdown of my change makes it look like I did a lot more to the code than I actually did. I think it's just fussy because I extracted the method on the child UL menu builder.

Other than that the changes are subtle.  Here's the working change from the local package build with breaks in both the menu and the drop down:

Capture

Cheers.

**Comment by MisterJames** [comment]
Also a fix in there for missing the KeyAttribute, and a fail over for folks that don't attribute primary keys (common in EF code first).

**Comment by erichexter** [comment]
looks like this has a conflict with the areas support I just put in.  Can you merge and resubmit ?

**Comment by MisterJames** [comment]
Will do, I'll address it in the AM.

Cheers.

**Comment by MisterJames** [comment]
Can you give it a try again? Looks like I've got it sorted.  Cheers.

**Pull request merged**
