### PR TITLE
Template review: code templates should match the default scaffolding

### PR DESCRIPTION
**Pull request by serra**
I'll use this pull request to port back some changes I made to the templates.
### Notes

Depends on pull #65 (confirm delete)
### Tasks
- [x] review `ControllerWithContext.cs.tt` bug, see #57 only namespace addition needed 5075381
- [x] all view templates should match the ones in `_views\shared`
  - [x] Create
  - [x] Details
  - [x] Index (list.tt
  - [x] What to do with Edit -> I chose to simply copy the `Create.tt`
  - [x] Delete
- [x] Annoying: Having to manually remove the "custom tool" from the .tt files (otherwise we get a compile error)
- [x] Annoying: Having to close and open solution to remove build errors in temporary files

### CODE REVIEW

**Comment by erichexter** [comment]
so.. what would make it easier... creating a sample project that can run
with the files before they are transformed into the .pp extensions.. so we
can develop this inline and extract the package?
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

On Wed, Dec 5, 2012 at 4:55 AM, Marijn van der Zee <notifications@github.com

> wrote:
> 
> ime consu

**Comment by serra** [comment]
Sounds good. Such a project could also serve to "communicate" the goals and concerns of the project too (see #27). E.g.:
- developers can use any type of (view)model and twitter.bootstrap.mvc just works, no restrictions 
- twitter.bootstrap.mvc does not require any additional dependencies outside of the ui layer
- ...

**Comment by erichexter** [comment]
I created a separate nuget for the templates.. 

as far as making it easier to back port changes..  this is the process you can use

modify the templates your using..
copy them into the bootstrap folder
from a separate vs instance run the build.ps1 from the nuget console.. then do a install-package for the .templates package.

you can also automate this process like i did in the test\endtoend\tests.ps1 file.. I run that from a nuget console in a separate instance of vs and I can easily try out the packages that the build.ps1 creates in a new solution.

**Comment by serra** [comment]
That would work. I'll give have a look at it somewhere in the next couple of weeks.
My first goal would be to make sure the templates exactly match their corresponding defaults in `~/Views/Shared`.

Nice work!

**Comment by erichexter** [comment]
should i merge this or are you just reviewing it?

**Comment by serra** [comment]
I'd like to get all tasks checked before you merge. I'll reopen when done. Code templates are useful, but only if they match the default scaffolding.

And don't produce annoying compile errors, that's a big turn-off for me ATM.

**Comment by serra** [comment]
@erichexter @MisterJames please consider accepting this pull, or add some feedback for me, so I can approve it. It's kind of blocking further improvements; e.g.#79 #89.

**Pull request merged**
