### PR TITLE
Added optional 'path' input parameter to build.ps1

### PR DESCRIPTION
**Pull request by devlife**
I've never worked with an upstream repo before.  Hopefully I did it correctly.

I added an optional 'path' input parameter to build.ps1 to make it
easier for developers to test.

> > .\build.ps1 "C:\Users\blah\Desktop\NugetPackages\bootstrap.mvc"

I also cleaned up the script a little bit.

### CODE REVIEW

**Comment by devlife** [comment]
Hmm.  Maybe I should have rebased instead of merged?

**Comment by erichexter** [comment]
I will manually merge this..

**Comment by devlife** [comment]
Was I supposed to rebase instead of merge?

**Comment by erichexter** [comment]
the rebase would have helped but it took so long for me to do it... its not a big deal

**Comment by erichexter** [comment]
committed in 18b452ebf99138e52497ab6998630c322ab9910a

**Comment by erichexter** [comment]
I appreciate your pull request, will please submit this contributor agreement. http://sdrv.ms/13eMRXm this will help keep the project compliant with our open source license.

**Comment by devlife** [comment]
Submitted

**Comment by erichexter** [comment]
thanks!

**Pull request closed without merging**
