### PR TITLE
fix issue for jquery error when installing nuget package.

### PR DESCRIPTION
**Pull request by kmiloaguilar**

### CODE REVIEW

**Comment by erichexter** [comment]
after this merges it should auto publish to a myget feed, can test it from there.

**Comment by kmiloaguilar** [comment]
The views need to be updated. I will work on that and submit a pull request soon. Ideas about the navigations files issue?

**Comment by erichexter** [comment]
the navigation was blown away when we were separating the project(s).

Here is the myget feed we can use to test what is merged into master. Once
we feel the package works, I can publish the packages from this private
feed into the public nuget feed.

https://www.myget.org/F/erichexter/

**Comment by kmiloaguilar** [comment]
what was the other project?

**Pull request merged**
